### ISSUE TITLE
Modman remove not working properly with copy deploy

### ISSUE THREAD

**Issue by raphaelpetrini** [colinmollenhour/modman#102]
If we deploy a module like this:

```modman clone --copy My_Module git@bitbucket.org:me/my_module.git```

And then run

```modman remove My_Module```

Then files deployed via copy are not deleted.

Any way I can get this working ?

**Comment by jhoelzl** [comment]
Please run the comman `modman undeploy My_Module` before `modman remove My_Module`

**Comment by raphaelpetrini** [comment]
Doesn't fix the issue, files are still present.

Again as I'm using the copy setting, I expect the files copied under app/code, app/design, app/etc/modules etc... to be deleted when I run remove but it is not working.

I reckon the remove command only remove from the modman folder and does not take care of the mapped files.

**Comment by jhoelzl** [comment]
Maybe the command `modman undeploy` does not work anymore because the files in the modman folder are already removed with the command `modman remove`? Maybe add again the files under the modman folder and try again.

**Comment by raphaelpetrini** [comment]
I don't think that would be the case as I tried to run modman undeploy BEFORE modman remove as you suggested.

**Comment by colinmollenhour** [comment]
I don't think `--copy` is really compatible with `remove` because it is not really feasible to know with 100% accuracy which files are safe to delete. I would suggest examining if you really require the use of `--copy` and seek alternative solutions.

**Comment by treck** [comment]
Try `modman deploy --force <MODULE>` first to overwrite hardcopied files with symlinks and then `modman undeploy <MODULE>` to delete the symlinks again followed by `modman remove <MODULE>`.
That worked for me.

**Comment by waynetheisinger** [comment]
What I do is do `modman update` to temporarily change to symlinks, then do `modman remove` which removes the symlinks - works for me.
