### ISSUE TITLE
Modman link problem when resolving phtml templates on 1.9.2.4

### ISSUE THREAD

**Issue by zdraganov** [colinmollenhour/modman#113]
> Setup:
> Magento 1.9.2.4
> Module Manager (v1.12)

The problem is only when using modman link feature. When I pack and install plugin from archive it works well.

The system.log says
> Not valid template file:adminhtml/default/default/template/metrilo/system/config/button.phtml

The actual file is located in `app/design/adminhtml/default/default/template/metrilo/system/config/button.phtml`

**Comment by ExtensionsStore** [comment]
Yeah, you need to enable symlinks: http://screencast.com/t/kK07B25fwm
