### ISSUE TITLE
unable to install modman in windows OS

### ISSUE THREAD

**Issue by gt06** [colinmollenhour/modman#124]
i have read documentation of modman. but i am not getting exactly what will have to take the steps for implementing the modman.
i am new to sound of magento as well as modman.
can anyone tell me the exact steps.

**Comment by ThomasNegeli** [comment]
Have you seen https://github.com/colinmollenhour/modman#windows-users

**Comment by colinmollenhour** [comment]
There might be limited use for it within Ubuntu on Windows now that the latest version is pretty decent, but this is still highly dependent on how you setup your environment and something I wouldn't recommend for a beginner. In general modman was designed to be used in a Linux environment so if you are a Windows user I recommend using VirtualBox or similar to setup your environment.

**Comment by barbazul** [comment]
We have been using stewards/modman-php for the windows-based members of our team with some success.

However, it is not a REAL port of modman, so some commands do not run exactly as you would expect them to
