### ISSUE TITLE
Trying to understand

### ISSUE THREAD

**Issue by DocOlson** [colinmollenhour/modman#128]
Hi,

I'm having issues wrapping my head around this.

This is my (intended) setup:

I have a shop instance which is a working copy of a repository. The underlying repository has a post-receive hook which automatically checks out the entire repository and deploys to the live or staging server (depending on the branch) using rsync.

This works fine so far. Now I would like to use modman.

Inside the working copy I have the .modman folder with all the modules each cloned from their respective repository. My intention is to work on the shop's instance and also on the modules if necessary. For instance when I see a bug in a module, I fix and commit it from within the current project. From other projects a simple "git pull" should incorporate those bugfixes/changes into those projects.

"modman deploy-all" works fine locally but when I push to master or stage branch the automated checkout ignores the contents of the modules inside the .modman folder.

So the checked out .modman folder looks like this:

.modman/module1 -> empty
.modman/module2 -> empty

and so on...

I figure this has to do with the fact that those are git repositories within another git repository.

I guess I am missing something here?

**Comment by colinmollenhour** [comment]
I don't really understand the issue, but rsync can copy symlinks and modman uses relative symlinks for just this reason (so you can rsync the symlinks and they will still work if the roots are different).

> the automated checkout ignores the contents of the modules inside the .modman folder

This sounds like an issue that is not really related to the modman script itself.
