### ISSUE TITLE
Override module name to clone repositories with the same name

### ISSUE THREAD

**Issue by tomlankhorst** [colinmollenhour/modman#130]
It would be nice to have an additional optional argument for `modman clone` such as: 

`modman clone <repo-url> (<repo-name>)`

This will enable us to clone repositories that bear the same name ('magento' for example).

**Comment by colinmollenhour** [comment]
This is already the current behavior except the order of arguments is backwards.

```
modman clone <repo-url>  # uses module name from repo url
modman clone <module-name> <repo-url>
```

**Comment by tomlankhorst** [comment]
You are right and let me thank you a lot for your effort! My suggestion
would be to add optional arguments like these to the built in help text.

**Comment by colinmollenhour** [comment]
It is documented in a way using somewhat standard conventions:

```
Module Commands:
  modman <command> [<module>] [<options>] [[--] <VCS options>]
```

In your case `<command>` is 'clone' and `[<module>]` is the optional (as denoted by []) specification of a module name and `[<options>]` is the command options which in the case of 'clone' is the repo url. But I'll concede that it is not obvious. :)
