### ISSUE TITLE
modman undeploy-all and remove-all

### ISSUE THREAD

**Issue by jhoelzl** [colinmollenhour/modman#86]
Is it possible to provide a functionality like "undeploy-all" and "remove-all" in regards to the existing function deploy-all?

Thanks!

**Comment by pocallaghan** [comment]
I'd be willing to take a crack at implementing this if colin is open to the suggestion?

**Comment by colinmollenhour** [comment]
Go for it.

**Comment by jhoelzl** [comment]
Hi @pocallaghan, do you have time to provide a basic impementation of these commands? Would be very nice.. Thanks!

**Comment by pocallaghan** [comment]
Hi @jhoelzl,

Unfortunately I'm totally snowed under with work ATM.

**Comment by jhoelzl** [comment]
OK, i have made a small shell script for my purpose that loops through the modman folders end performs the command `modman undeploy`. This works for me.

**Comment by richdel** [comment]
Currently I use a 'one liner' to handle undeploying all modules. When in the .modman directory run:

```
modman list | while read ext; do (modman undeploy $ext); done
```

**Comment by colinmollenhour** [comment]
That's the kind of thing modman list was added for. Does that method allow stdin from the user? I think it wouldn't, but maybe that is why you use the subshell? I've always preferred:

    for ext in $(modman list); do modman undeploy $ext; done

Which does not use pipes so does not interfere with stdin. It is rare to need stdin, such as when you have a @shell script that needs a password or similiar.

**Comment by richdel** [comment]
I'm not so sure sorry, my knowledge of bash scripting is a little limited and I was looking for a solution to quickly undeploy all modules and that's what I came up with...

**Comment by snez** [comment]
This is the first result in Google when searching for the functionality. modman undeploy works, the issue can be closed and the feature can be added to the documentation.

**Comment by colinmollenhour** [comment]
undeploy is documented in the usage: https://github.com/colinmollenhour/modman/blob/master/modman#L60
