### ISSUE TITLE
modman is cool, but --force should be warning

### ISSUE THREAD

**Issue by hellomaya** [colinmollenhour/modman#93]
I have tried modman, and it's really cool, thanks for your good work.

In one of my mistakes, I used the same path name with core frontend template folder and files, when I run modman deploy-all --force, the core frontend template folder is deleted too, well I think we should put some warning message on tutorials or README, that could be a rookie mistake and a disaster...

Thanks.

**Comment by colinmollenhour** [comment]
I think it should be a given that you should not use the `--force` lightly. E.g. I would hope you don't `git push --force` out of habit too or you're just asking for more pain.
