### ISSUE TITLE
where is modman 

### ISSUE THREAD

**Issue by farmaworld** [colinmollenhour/modman#94]
iMac-di-Raffaele-Filomena:magento raffaele$ curl -s -L https://raw.github.com/colinmollenhour/modman/master/modman-installer
# !/usr/bin/env bash

if [ ! -d "$HOME/bin" ] ; then
    mkdir $HOME/bin

```
if [ -f $HOME/.profile ]; then
    tty -s && . $HOME/.profile

    if [[ ":$PATH:" != *":$HOME/bin:"* ]]; then
        echo -e '\nPATH="$HOME/bin:$PATH"' >> $HOME/.profile
    fi
fi
```

fi

SRC="https://raw.githubusercontent.com/colinmollenhour/modman/master/modman"
DEST="$HOME/bin/modman"
# test if curl/wget is installed

if hash curl 2>&- ; then
    CMD="curl -s -L $SRC -o $DEST"
elif hash wget 2>&- ; then
    CMD="wget -q --no-check-certificate -O $DEST $SRC"
else
   echo "You need to have curl or wget installed."
   exit 1
fi

$CMD

chmod +x $DEST

echo "Done. Modman installed in $HOME/bin/modman"

where is dir installation?
thanks

**Comment by pocallaghan** [comment]
Not sure I understand the question. The command you ran won't have installed it, you curl the installer and don't do anything with it, the contents is just output to the screen. If you run the full command from the README which redirects the content to bash, the installer script should attempt to place modman in a bin directory in your home directory, i.e. in `~/bin`.

**Comment by farmaworld** [comment]
why the installation did not work? what is the problem?

**Comment by pocallaghan** [comment]
As I said. You didn't run the whole command. What you posted shows you started with `curl`, the README shows it starting with `bash`.

**Comment by farmaworld** [comment]
ok thanks i have installed 
Done. Modman installed in /Users/raffaele/bin/modman
but for use whith my magento is good that dir?

**Comment by pocallaghan** [comment]
It doesn't really matter where it's located, it goes in that directory by default as it's a reasonable default location. So long as running `which modman` shows that path, you should be fine. The install script attempts to ensure `~/bin` is in your `PATH` so you should be fine.

**Comment by farmaworld** [comment]
./modman clone ApiImport https://github.com/danslo/ApiImport.git
Module Manager directory not found.
Run "modman init" in the root of the project with which you would like to use Module Manager.
iMac-di-Raffaele-Filomena:bin raffaele$

**Comment by pocallaghan** [comment]
If you wish to use modman to install a module, you need to be in you need to be in your Magento root directory, not the the bin directory. To start using modman you first have to call `init` which will create the `.modman` directory for you where the checked out modules will go. There is only one argument to clone, which is the path to the git repo you wish to clone.

```bash
cd ~/My/Site/Directory
modman init
modman clone https://github.com/danslo/ApiImport.git
```

I suggest you [read through the wiki](https://github.com/colinmollenhour/modman/wiki/Tutorial).

**Comment by farmaworld** [comment]
in my magento directory, as you say, I always command not found

**Comment by pocallaghan** [comment]
Then `~/bin` is not in your `PATH` variable. The `PATH` variable is a semicolon seperate list of directories in which the OS will look for commands. Things to try:

Run `echo  $PATH` and check to see if it includes `/Users/raffaele/bin`.
Run `cat ~/.profile` and see if it it contains something along the lines of `PATH="$HOME/bin:$PATH`. If it does run `source ~/.profile` (as per the README) and try using modman again.

If you can't work out what you're doing with the `PATH` stuff, you can just use the full path to the modman file `~/bin/modman init` etc. or copy the modman file into your directory.

```bash
cp ~/bin/modman /your/project/dir/
modman init
```

**NB:** None of this is directly related to modman, this is core terminal functionality.

**Comment by colinmollenhour** [comment]
Maybe the installer should first attempt to install to a location like /usr/local/bin to avoid having to modify the PATH?

**Comment by dougmays** [comment]
I'd like to piggy back off this  thread because it helped me move the modman folder from my /bin to my project folder using your supplied command (i dont have alot of terminal knowledge)
cp ~/bin/modman /your/project/dir/
modman init

But...it moved the folder correctly so i have the modman folder in my project, but modman init is giving me the error "Dougs-Mac-mini:magento DougCharterContact$ modman init
-bash: modman: command not found"

Any idea why it  wont initialize? Thanks...Doug

**Comment by colinmollenhour** [comment]
You actually don't want the modman script in your project folder, or at least I can't think of any good reason why.. Do this:

    $ echo $PATH

And then place the modman script into one of those directories that are included in your $PATH and make sure it has the executable mode set (e.g. chmod 755 /path/to/modman).

**Comment by dougmays** [comment]
yikes now i think i'm all messed up because when i rerun the bash command from your install read me it doesnt download modman to Bin like it did before i ran the 'cp' to move it

**Comment by dougmays** [comment]
update....modman is in the ~/bin directory. I ran chmod 755 on that 'modman' folder. went to my projects folder and ran modman init...and received the 'command not found' message. Any ideas? :/

**Comment by colinmollenhour** [comment]
I was referring to modman the file, not the modman git repo directory. So ~/bin/modman should be a *file*.

**Comment by dougmays** [comment]
Yep the modman file is in the ~/bin directory. And i ran chmod on it. but running modman init in my Project folder is giving me the "command not found" message.

**Comment by colinmollenhour** [comment]
Sounds like your shell still isn't finding modman in your PATH. See: http://www.linfo.org/path_env_var.html

**Comment by savadivirender** [comment]
modman initiated successfully but i'm getting following error
line 1180: git: command not found

**Comment by colinmollenhour** [comment]
You need to have git in your path.
