### ISSUE TITLE
Modman changes not showing up

### ISSUE THREAD

**Issue by nielsdebruin** [colinmollenhour/modman#98]
Currently I have a modman enabled module which I installed on my local development server. I would like to make some changes to it and see how they turn out. However when I make a change to the .modman/mymodule folder nothing changes in the magento site. I tried commiting the changes but that didn't seem to help either. They only way I can get it to change is to remove the entire module and clone it again... When I `cat` the changed file content using its symblic link (created by modman) I do see the changes to it. So it seems that the links are working, so why does magento not change?

Cache: disabled
Symlinks: on
Platform: Vagrant on OSX yosemite, (linux box)

**Comment by colinmollenhour** [comment]
Cache?

**Comment by nielsdebruin** [comment]
Disabled, and i tried flushing

**Comment by pocallaghan** [comment]
What changes specifically don't appear to be working? Could it be opcode cache?

**Comment by nielsdebruin** [comment]
@pocallaghan Tried resetting that no luck.

Well is does not appear to reload (stylesheet). I spent an entire day trying to figure it out, however no luck. Then I just changed my vagrant image for a different one and it seems to work as intended. Mabye the other image has some obscured way of caching as suggested. Anyways it does not seem to be a modman issue after all.
